version: "3.10"
services:
  worker:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - CHANNEL_ID=${CHANNEL_ID}
      - DATABASE_URI=${DATABASE_URI}
      - OWNER_ID=${OWNER_ID}
      - FORCE_SUB_CHANNEL=${FORCE_SUB_CHANNEL}
      - FORCE_SUB_MESSAGE=${FORCE_SUB_MESSAGE}
      - START_MESSAGE=${START_MESSAGE}
